#!/usr/bin/env python3
"""Fetch a small, pinned snapshot of the official SLO curriculum-fo dataset.

The script intentionally stores raw source data + hashes. It does not invent or
rewrite curriculum IDs. By default it fetches only the collections LeerSprong
needs for curriculum mapping and avoids the very large deprecated/illustration
collections.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import urllib.request
from datetime import datetime, timezone
from typing import Any

GITHUB_API = "https://api.github.com"
RAW_GITHUB = "https://raw.githubusercontent.com"
DEFAULT_REPO = "slonl/curriculum-fo"
DEFAULT_REF = "main"
DEFAULT_COLLECTIONS = (
    "kernzinnen.json",
    "doelzinnen.json",
    "domeinen.json",
    "subdomeinen.json",
    "sets.json",
)


def fetch_bytes(url: str, timeout: int = 30) -> bytes:
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json, application/json",
            "User-Agent": "LeerSprong-NL-curriculum-sync/1.0",
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def fetch_json(url: str, timeout: int = 30) -> Any:
    return json.loads(fetch_bytes(url, timeout).decode("utf-8"))


def resolve_ref(repo: str, ref: str, timeout: int = 30) -> str:
    payload = fetch_json(f"{GITHUB_API}/repos/{repo}/commits/{ref}", timeout)
    sha = payload.get("sha")
    if not isinstance(sha, str) or len(sha) < 7:
        raise RuntimeError(f"Could not resolve {repo}@{ref} to a commit SHA")
    return sha


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sync(
    output_dir: pathlib.Path,
    repo: str = DEFAULT_REPO,
    ref: str = DEFAULT_REF,
    collections: tuple[str, ...] = DEFAULT_COLLECTIONS,
    timeout: int = 30,
) -> dict[str, Any]:
    commit_sha = resolve_ref(repo, ref, timeout)
    output_dir.mkdir(parents=True, exist_ok=True)

    files: list[dict[str, Any]] = []
    for filename in collections:
        url = f"{RAW_GITHUB}/{repo}/{commit_sha}/data/{filename}"
        raw = fetch_bytes(url, timeout)
        # Fail early if the upstream file is no longer valid JSON.
        json.loads(raw.decode("utf-8"))
        target = output_dir / filename
        target.write_bytes(raw)
        files.append(
            {
                "name": filename,
                "source": url,
                "bytes": len(raw),
                "sha256": sha256(raw),
            }
        )

    manifest = {
        "sourceRepository": f"https://github.com/{repo}",
        "requestedRef": ref,
        "commitSha": commit_sha,
        "fetchedAt": datetime.now(timezone.utc).isoformat(),
        "files": files,
        "notes": [
            "Raw official SLO curriculum data; no IDs are generated by LeerSprong.",
            "SLO Open Data contains curriculum goals, not lessons or assessments.",
            "Check source licensing/attribution requirements before redistributing snapshots.",
        ],
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="curriculum/slo/raw", help="Snapshot output directory")
    parser.add_argument("--repo", default=DEFAULT_REPO, help="GitHub owner/repository")
    parser.add_argument("--ref", default=DEFAULT_REF, help="Branch, tag or commit")
    parser.add_argument("--timeout", type=int, default=30)
    parser.add_argument(
        "--collections",
        nargs="+",
        default=list(DEFAULT_COLLECTIONS),
        help="File names under upstream data/",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = sync(
        pathlib.Path(args.out),
        repo=args.repo,
        ref=args.ref,
        collections=tuple(args.collections),
        timeout=args.timeout,
    )
    print(
        f"SLO snapshot pinned to {manifest['commitSha']} "
        f"({len(manifest['files'])} files) -> {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
