import type { LearningActivity } from '../activity-engine';

export const G4_MULTIPLICATION_SKILL_ID = 'g4-math-multiplication-foundations';

export const g4MultiplicationLesson = {
  id: 'g4-math-multiplication-foundations-v1',
  title: 'Tafels begrijpen',
  subtitle: 'Van groepjes maken naar slim vermenigvuldigen',
  group: 4,
  skillId: G4_MULTIPLICATION_SKILL_ID,
  estimatedMinutes: 12,
  goal: 'Ik kan vermenigvuldigen uitleggen als gelijke groepjes en eenvoudige keersommen oplossen.',
  activities: [
    {
      id: 'g4-mul-01',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'multiple-choice',
      prompt: 'Er staan 3 mandjes met in elk mandje 4 appels. Welke som past hierbij?',
      options: ['3 + 4', '3 × 4', '4 − 3'],
      correctOption: 1,
      explanation: '3 gelijke groepjes van 4 schrijf je als 3 × 4.',
      difficulty: 1,
      tags: ['gelijke-groepjes', 'betekenis'],
    },
    {
      id: 'g4-mul-02',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'fill-blank',
      prompt: 'Vul in: 5 groepjes van 2 is samen ___.',
      acceptedAnswers: ['10'],
      explanation: '5 × 2 = 10. Je kunt ook 2 + 2 + 2 + 2 + 2 rekenen.',
      difficulty: 1,
      tags: ['herhaald-optellen'],
    },
    {
      id: 'g4-mul-03',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'multiple-choice',
      prompt: 'Wat is 4 × 6?',
      options: ['20', '24', '28'],
      correctOption: 1,
      explanation: '4 groepjes van 6 zijn samen 24.',
      difficulty: 2,
      tags: ['tafels'],
    },
    {
      id: 'g4-mul-04',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'ordering',
      prompt: 'Zet de stappen in de goede volgorde om 3 × 5 uit te rekenen.',
      items: ['Tel alles bij elkaar', 'Maak 3 gelijke groepjes', 'Doe 5 in elk groepje'],
      correctOrder: ['Maak 3 gelijke groepjes', 'Doe 5 in elk groepje', 'Tel alles bij elkaar'],
      explanation: 'Een keersom beschrijft eerst hoeveel groepjes je hebt en daarna hoeveel er in elk groepje zitten.',
      difficulty: 2,
      tags: ['strategie', 'betekenis'],
    },
    {
      id: 'g4-mul-05',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'multiple-choice',
      prompt: 'Welke twee sommen hebben dezelfde uitkomst?',
      options: ['3 × 4 en 4 × 3', '3 × 4 en 3 + 4', '4 × 3 en 4 + 3'],
      correctOption: 0,
      explanation: '3 × 4 en 4 × 3 zijn allebei 12. De groepjes zijn anders verdeeld, maar het totaal is gelijk.',
      difficulty: 3,
      tags: ['wisselregel', 'inzicht'],
    },
    {
      id: 'g4-mul-06',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'fill-blank',
      prompt: 'Je weet dat 5 × 6 = 30. Wat is dan 6 × 5?',
      acceptedAnswers: ['30'],
      explanation: 'Bij vermenigvuldigen mag je de factoren omwisselen: 5 × 6 = 6 × 5.',
      difficulty: 3,
      tags: ['wisselregel'],
    },
    {
      id: 'g4-mul-07',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'multiple-choice',
      prompt: 'Een klas heeft 7 tafels. Aan elke tafel zitten 4 kinderen. Hoeveel kinderen zijn dat?',
      options: ['11', '24', '28'],
      correctOption: 2,
      explanation: '7 gelijke groepjes van 4: 7 × 4 = 28.',
      difficulty: 4,
      tags: ['verhaalsom', 'transfer'],
    },
    {
      id: 'g4-mul-08',
      skillId: G4_MULTIPLICATION_SKILL_ID,
      kind: 'fill-blank',
      prompt: 'Een doos heeft 8 rijen met 6 stickers. Hoeveel stickers zijn er?',
      acceptedAnswers: ['48'],
      explanation: '8 × 6 = 48. Je kunt bijvoorbeeld 4 × 6 verdubbelen.',
      difficulty: 5,
      tags: ['verhaalsom', 'strategie'],
    },
  ] satisfies LearningActivity[],
};
